In [8]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
pd.options.display.max_columns = None
df = pd.read_csv("./berlin-airbnb-data/listings_summary.csv")

In [10]:
df.describe(include="all")

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
count,2.255200e+04,22552,2.255200e+04,22552,22493,21589,14020,22349,22552,11540,7215,13036,10837,10406,11449,0.0,0.0,22552,0.0,2.255200e+04,22552,22526,22526,22436,11189,9658,9657,0.0,22526,22526,22526,17458,22526.000000,22526.000000,22552,22526,22526,22552,21421,22552,22552,22547,22468,21896,22489,22552,22552,22552,22552.000000,22552.000000,22552,22552,22552,22552.000000,22520.000000,22534.000000,22512.000000,22552,22552,446.000000,22552,3681,2659,13191,15406,22552.000000,22552,22552.000000,2.255200e+04,22552,22552,22552.000000,22552.000000,22552.000000,22552.000000,22552,22552.000000,18638,18644,18163.000000,18138.000000,18141.000000,18120.000000,18134.000000,18121.000000,18117.000000,22552,1638,0.0,22552,22552,22552,22552,22552,22552.000000,18638.000000
unique,NaN,22552,NaN,2,21873,21041,13598,21997,1,10781,6687,12308,9946,9584,10350,NaN,NaN,22465,NaN,NaN,19180,5997,2914,1036,8879,4,64,NaN,2,19100,19100,181,NaN,NaN,301,2,2,86,91,136,12,60,19,215,6,61,1,1,NaN,NaN,2,33,3,NaN,NaN,NaN,NaN,5,19985,NaN,295,387,426,142,112,NaN,65,NaN,NaN,75,1,NaN,NaN,NaN,NaN,2,NaN,2228,1312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1387,NaN,2,1,5,2,2,NaN,NaN
top,NaN,https://www.airbnb.com/rooms/21236833,NaN,2018-11-07,Berlin Wohnung,"with en-suite bathroom, TV, WIFI, bed linen, a...",The Singer 109 Hostel is located in the heart ...,"with en-suite bathroom, TV, WIFI, bed linen, a...",none,Welcome Traveler. The Singer Hostel and Apart...,Since 01.01.2014 the city of Berlin had to ado...,U-Bahn / Underground /Subway / Metro: U5 (Stra...,We can offer our guests - Pool table/Snooker -...,There is always at least 1 member of staff on ...,- No shoes in the house,NaN,NaN,https://a0.muscache.com/im/pictures/67c5efca-2...,NaN,NaN,https://www.airbnb.com/users/show/1625771,Anna,2013-08-19,"Berlin, Berlin, Germany",.,within an hour,100%,NaN,f,https://a0.muscache.com/defaults/user_pic-50x5...,https://a0.muscache.com/defaults/user_pic-225x...,Neukölln,NaN,NaN,"['email', 'phone', 'reviews']",t,f,"Berlin, Berlin, Germany",Neukölln,Tempelhofer Vorstadt,Friedrichshain-Kreuzberg,Berlin,Berlin,10245,Berlin,"Berlin, Germany",DE,Germany,NaN,NaN,t,Apartment,Private room,NaN,NaN,NaN,NaN,Real Bed,{},NaN,$30.00,$300.00,"$1,200.00",$0.00,$0.00,NaN,$0.00,NaN,NaN,today,t,NaN,NaN,NaN,NaN,2018-11-07,NaN,2017-05-28,2018-11-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,HRB155306B,NaN,f,f,flexible,f,f,NaN,NaN
freq,NaN,1,NaN,22549,14,14,41,12,22552,43,37,26,42,43,30,NaN,NaN,3,NaN,NaN,45,216,51,17188,71,5081,7127,NaN,19515,56,56,2556,NaN,NaN,4103,22470,13824,22317,3209,1325,5497,22417,22417,855,22483,22419,22552,22552,NaN,NaN,16776,20225,11534,NaN,NaN,NaN,NaN,21766,75,NaN,1387,232,143,5319,1865,NaN,10863,NaN,NaN,2517,22552,NaN,NaN,NaN,NaN,22549,NaN,116,618,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22544,35,NaN,15518,22552,9102,22396,22273,NaN,NaN
mean,1.571560e+07,NaN,2.018111e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.403355e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.330685,2.330685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.509824,13.406107,NaN,NaN,NaN,2.637460,1.092695,1.161134,1.620558,NaN,NaN,465.401345,NaN,NaN,NaN,NaN,NaN,1.332121,NaN,7.157059,1.030505e+05,NaN,NaN,4.944173,11.146639,20.016096,79.852829,NaN,17.840679,NaN,NaN,94.413863,9.663965,9.324955,9.713521,9.730672,9.505491,9.411106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.918233,1.135525
std,8.552069e+06,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.816290e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.947823,19.947823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.030825,0.057964,NaN,NaN,NaN,1.510548,0.329894,0.646156,1.174840,NaN,NaN,503.491935,NaN,NaN,NaN,NaN,NaN,0.835034,NaN,40.665073,9.640519e+06,NaN,NaN,8.677395,17.522371,28.349136,119.368162,NaN,36.769624,NaN,NaN,7.639644,0.740039,1.031996,0.704620,0.686614,0.762161,0.841492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.667257,1.507082
min,2.015000e+03,NaN,2.018111e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.217000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.345803,13.103557,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,1.000000e+00,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,NaN,NaN,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.010000
25%,8.065954e+06,NaN,2.018111e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.240002e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.489065,13.375411,NaN,NaN,NaN,2.000000,1.000000,1.000000,1.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,2.000000,2.000000e+01,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,NaN,NaN,92.000000,10.000000,9.000000,10.000000,10.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.180000
50%,1.686638e+07,NaN,2.018111e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.126711e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.509079,13.416779,NaN,NaN,NaN,2.000000,1.000000,1.000000,1.000000,NaN,NaN,403.500000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,2.000000,1.124000e+03,NaN,NaN,0.000000,0.000000,0.000000,4.000000,NaN,5.000000,NaN,NaN,97.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.540000
75%,2.258393e+07,NaN,2.018111e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.067518e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.532669,13.439259,NaN,NaN,NaN,3.000000,1.000000,1.000000,2.000000,NaN,NaN,707.500000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,4.000000,1.125000e+03,NaN,NaN,6.000000,18.000000,36.000000,129.000000,NaN,16.000000,NaN,NaN,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.500000
max,2.986735e+07,NaN,2.018111e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.245081e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1676.000000,1676.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.651670,13.757642,NaN,NaN,NaN,16.000000,8.500000,12.000000,22.000000,NaN,NaN,4639.000000,NaN,NaN,NaN,NaN,NaN,16.000000,NaN,5000.000000,1.000000e+09,NaN,NaN,30.000000,60.000000,90.000000,365.000000,NaN,498.000000,NaN,NaN,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.000000,36.670000

In [11]:
#first lets get started and remove all the data that DEFINITELY not needed for analysis
#like the listing_url,scraped data, scraped id, name
#Also trying to remove any sections that has summary in it, since we are not going to include Text-Processing based results in prediction
##Check if reviews could be used dropping them for now,
replace_dollar_symbols = True
drop_columns = True

In [12]:
df["amenities"]

0        {TV,"Cable TV",Wifi,Kitchen,Gym,Heating,"Famil...
1        {Wifi,Kitchen,Elevator,Heating,Washer,Essentia...
2        {Internet,Wifi,Kitchen,"Buzzer/wireless interc...
3        {Internet,Wifi,"Pets allowed","Pets live on th...
4        {Wifi,Heating,"Family/kid friendly",Essentials...
                               ...
22547    {Wifi,"Smoking allowed",Heating,Essentials,Sha...
22548    {TV,Wifi,Kitchen,"Free parking on premises","F...
22549    {Wifi,Kitchen,Heating,Washer,"Fire extinguishe...
22550    {Wifi,"Paid parking off premises",Doorman,Elev...
22551    {Wifi,"Air conditioning",Kitchen,Breakfast,Hea...
Name: amenities, Length: 22552, dtype: object

In [ ]:
columns_to_be_deleted = ["listing_url", "host_total_listings_count", "scrape_id", "experiences_offered", "last_scraped", "name", "host_acceptance_rate", "summary", "space", "description", "neighborhood_overview", "notes", "transit",  "access", "interaction", "house_rules", "thumbnail_url", "medium_url", "picture_url",  "xl_picture_url",  "host_id", "host_url", "host_name", "host_since", "host_location", "host_about", "host_response_time", "host_response_rate","host_thumbnail_url", "host_picture_url",  "host_neighbourhood", "host_listings_count", "host_verifications", "host_has_profile_pic", "host_identity_verified", "street","neighbourhood_cleansed", "neighbourhood_group_cleansed", "city", "state", "market", "smart_location", "country_code", "country", "amenities", "calendar_updated", "calendar_last_scraped", "first_review", "last_review", "license", "jurisdiction_names", "require_guest_profile_picture", "requires_license", "is_location_exact", "require_guest_phone_verification", "calculated_host_listings_count"]
review_columns = ["review_scores_value", "review_scores_rating", "review_scores_accuracy", "review_scores_cleanliness", "reviews_per_month", "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value"]

In [ ]:
if drop_columns:
    df.drop(columns_to_be_deleted, axis=1, inplace=True)
    df.drop(review_columns, axis=1, inplace=True)
    #Feature Engineering, remove all the occurances of '$' symbol
    drop_columns = False

In [ ]:
if replace_dollar_symbols:
    df.price = df.price.str.replace('$', '').str.replace(',', '').astype(float)
    df.weekly_price = df.weekly_price.str.replace('$', '').str.replace(',', '').astype(float)
    df.monthly_price = df.monthly_price.str.replace('$', '').str.replace(',', '').astype(float)
    df.cleaning_fee = df.cleaning_fee.str.replace('$', '').str.replace(',', '').astype(float)
    df.security_deposit = df.security_deposit.str.replace('$', '').str.replace(',', '').astype(float)
    df.extra_people = df.extra_people.str.replace('$', '').str.replace(',', '').astype(float)
    replace_dollar_symbols = False

In [ ]:
#Print the percentage of all missing values
(len(df)-df.count())/len(df)*100

In [ ]:
#We see we really have lot of missing values for the weekly_price and monthly_price column. Similarly the square_feet
df.drop(["weekly_price", "monthly_price", "square_feet"], axis=1, inplace=True)
#has_availability makes no sense, as its just one value in all columns, similar is the case with is_business_travel_ready
df.drop(["has_availability", "is_business_travel_ready"], axis=1, inplace=True)

In [ ]:
#Generate a Categorical and Numerical Column List
numerical_columns = []
categoical_columns = []
for column in df.columns:
    if df[column].dtype == 'object':
        categoical_columns.append(column)
    else:
        numerical_columns.append(column)

In [ ]:
print(numerical_columns)
print(categoical_columns)

In [ ]:
df[numerical_columns].describe()

In [ ]:
df[categoical_columns].describe()

In [ ]:
#Print the percentage of all missing values
(len(df)-df.count())/len(df)*100

In [ ]:
df["price"].describe()

In [ ]:
#Check the distribuition of price column
import seaborn as sns
sns.kdeplot(df['price'])

In [ ]:
fig, axs = plt.subplots(ncols=2, figsize=(16, 4))
fig.suptitle('Distribution of price (before and after removing high-priced outliers)')

# Before cleaning
x_axis=df['price'].dropna()
sns.distplot(pd.Series(x_axis, name='Price (before cleaning)'), ax=axs[0])

# Remove where price > 400
condition = df[df['price'] >400 ]
rows_to_drop = condition.index
print("You dropped {} rows.".format(condition.shape[0]))
df = df.drop(rows_to_drop, axis=0)
print("Dataset has {} rows, {} columns.".format(*df.shape))

#After cleaning
x_axis=df['price'].dropna()
sns.distplot(pd.Series(x_axis, name='Price  (after cleaning)'), ax=axs[1])

In [ ]:
#check how the lattitude and longitude vary

import seaborn as sns
 # use the function regplot to make a scatterplot
sns.regplot(y=df["latitude"], x=df["longitude"])
#sns.plt.show()

In [ ]:
df["availability_365"]

In [ ]:
fig, axs = plt.subplots(ncols=2, figsize=(24, 4))
fig.suptitle('Distribution of availability (before and after removing part-time listings)')

# Before cleaning
print(df[df['availability_365'] == 0])
sns.distplot(pd.Series(x_axis, name='Availability (before cleaning)'), ax=axs[0])

In [ ]:
df['property_type'].value_counts()

In [ ]:
property_mapping = {'Guesthouse':'Guesthouse', 'Apartment':'Apartment', 'Condominium':'others', 'Loft':'others','House':'Apartment','Serviced apartment':'others','Townhouse':'others','Boutique hotel':'others','Bed and breakfast':'others',
                    'Bungalow':'others','Boat':'others','Guest suite':'others','Other':'others','Island':'others',
                    'Hostel':'others','Train':'others','Camper/RV':'others','Houseboat':'others','Cabin':'others',
                    'Cottage':'others','Tiny house':'others','Chalet':'others','Castle':'others','Villa':'others',
                    'Aparthotel':'others','Hotel':'others','Tipi':'others','Resort':'others','In-law':'others',
                    'Cave':'others','Barn':'others','Pension (South Korea)':'others','Guesthouse':'others','Casa particular (Cuba)':'others','others':'others'}
df['property_type']=df['property_type'].map(property_mapping)

In [ ]:
df['property_type'].value_counts()

In [ ]:
plt.figure(figsize=(10, 16))
chart = sns.heatmap(df[numerical_columns].corr(), square=True, annot=True,cbar=False)
chart.set_xticklabels(chart.get_xticklabels(),rotation=45)
chart.set_yticklabels(chart.get_yticklabels(),rotation=45)
plt.show()

In [ ]:
sns.distplot(data_frame['price'],bins=20)